### PR TITLE
fix(base_iso3166): add codes of countries according to the code iso 3166

### PR DESCRIPTION
**Pull request by agb80**
modified res_country.py with the adjustments made for version 10 since it did not recognize the
two-letter code when inserting it for what it returned false. with this adaptation already shows the
codes to three characters according to the standard Iso 3166

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please cherry-pick the commit and adapt anything remaining instead of hijacking the change with your own commit.

**Comment by agb80** [comment]
@pedrobaeza done

**Comment by aitorbouzas** [comment]
@agb80 would you mind increasing the code coverage so this module can be merged?

**Comment by agb80** [comment]
I could add a test file that check code for one or two countries, is that ok?

**Review by yajo — APPROVED** [review]

**Comment by pedrobaeza** [comment]
> I could add a test file that check code for one or two countries, is that ok?

Yes, that should be enough

**Comment by pedrobaeza** [comment]
Merging as old one with at least the cherry-picking comment for having this in v8.

**Pull request merged**
