### PR TITLE
12.0 mig base unece

### PR DESCRIPTION
**Pull request by levkar**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check Travis and runbot status.

**Comment by levkar** [comment]
It is some other module (base_iso3166) that is causing the problem. would it be pycountry?

**Comment by pedrobaeza** [comment]
Please rebase now that the CI is correct.

**Comment by levkar** [comment]
now we have another problem.

**Comment by levkar** [comment]
I think it's ok now.

**Comment by astirpe** [comment]
Could you add [readme *.rst](https://github.com/OCA/maintainer-tools/tree/master/template/module/readme) fragments?

**Comment by levkar** [comment]
I am quite busy these days and I don't want anyone to wait for it. You can accept and do readme fragments as another PR or wait until i can spare time. thanks.

**Comment by pedrobaeza** [comment]
I think we should wait as in v11, there's being a refactoring (#60). I will retake this module for my own customers soon and reconduct this, so if you can wait, I'll take care.

**Comment by pedrobaeza** [comment]
Sorry, I have mixed modules: `unece` with `nace`. This one should be correct to be merged. Reviewing right now.

**Review by pedrobaeza — APPROVED** [review]
As this one is the base for the rest of the modules, I'm going to fast-track it.

**Pull request merged**
