### PR TITLE
[16.0][MIG] account_tax_unece: Migration to 16.0

### PR DESCRIPTION
**Pull request by syera94**
@alexis-via @astirpe  hey guys, could you please check this PR if it's OK for you.

### CODE REVIEW

**Review by bealdav — APPROVED** [review]

**Review by alexis-via — APPROVED** [review]

**Comment by alexis-via** [comment]
arf, stupid bot... I'm the declared maintainer !

**Comment by alexis-via** [comment]
Anyone with the super-powers to merge this?

**Comment by pedrobaeza** [comment]
/ocabot merge nobump
/ocabot migration account_tax_unece

Next time please modify the PR title to conform guidelines: `[16.0][MIG] account_tax_unece: Migration to 16.0`.

**Comment by bealdav** [comment]
@pedrobaeza it seems commit were done with `oca-port`

**Comment by pedrobaeza** [comment]
Well, the PR title is got from the branch, and it should be manually modified. Not doing it, it's the lazy option, coming from oca-port or manual process.

**Comment by bealdav** [comment]
FYI I'm lazy and proud of it :-)

**Comment by bealdav** [comment]
Why not modify oca-port ?

**Comment by pedrobaeza** [comment]
I don't think that's possible, unless GitHub offers a way through the URL to set the PR title.

**Comment by bealdav** [comment]
I think we should update oca-port to generate branch as `16.0-MIG-my-module` instead of `16.0-mig-my-module` and update guideline to this new rule
If not, I'm afraid you'll got spend 2 hours a day to ask people update their PR title

**Comment by pedrobaeza** [comment]
That's not correct. Even with that branch name, the PR title won't be correct, as it's extracted for PR title as `16.0 MIG my module`, leading that it you search for `my_module` to check if there's other opened PRs, you won't find them. And in any case, it's `module_migrator` the tool for doing migrations, not `oca-port` (although it makes one part of the work).

**Pull request merged**
