### PR TITLE
[16.0][MIG] base_iso3166: Migration to 16.0

### PR DESCRIPTION
**Pull request by ramiadavid**
No changes required

#139

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by etobella — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@sbidoul it seems the bot is having problems. Some comments are not processed. Maybe a glitch?

**Comment by sbidoul** [comment]
What glitch? :smile:

**Comment by pedrobaeza** [comment]
Look at https://github.com/OCA/community-data-files/pull/143#issuecomment-1318848199

No reaction from bot.

**Comment by sbidoul** [comment]
As usual, it's likely a delay in GitHub webhook deliveries.

**Comment by pedrobaeza** [comment]
Curious that my command works instantly and the other not yet.

**Pull request merged**
