### PR TITLE
[10.0] Use HttpCase base class in test, because I need it for edi modules

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by alexis-via** [comment]
This PR is needed for https://github.com/OCA/edi/pull/31

**Comment by alexis-via** [comment]
I restored all the get_pdf() tests in the edi project and Travis is green. So this is ready to merge.

**Comment by alexis-via** [comment]
@pedrobaeza Are you OK to merge this ?

**Comment by pedrobaeza** [comment]
Fast-tracking it

**Comment by alexis-via** [comment]
Thanks !

**Pull request merged**
