### PR TITLE
[18.0][MIG] account_tax_unece: Migration to 18.0

### PR DESCRIPTION
**Pull request by LucasTran380381**

### CODE REVIEW

**Comment by bosd** [comment]
@LucasTran380381 Thanks, can you please squash the translation commits accoridng to the migration guide?

**Comment by LucasTran380381** [comment]
> @LucasTran380381 Thanks, can you please squash the translation commits accoridng to the migration guide?

Squashed

**Review by henrybackman — APPROVED** [review]

**Review by bosd — APPROVED** [review]

**Review by sebalix — APPROVED** [review]

**Review by alexis-via — APPROVED** [review]
Works well. I proposed I small usability improvement in this PR: https://github.com/LucasTran380381/community-data-files/pull/4

**Comment by alexis-via** [comment]
base_unece is now merged. Could you rebase this PR and then I merge it.

**Comment by alexis-via** [comment]
@OCA-git-bot Hey, I'm the declared maintainer of the modified addons ! So you should let me merge !

**Comment by LucasTran380381** [comment]
> base_unece is now merged. Could you rebase this PR and then I merge it.

I rebased. Thanks

**Pull request merged**
