### PR TITLE
[18.0][MIG] base_unece: Migration to 18.0

### PR DESCRIPTION
**Pull request by LucasTran380381**

### CODE REVIEW

**Comment by bosd** [comment]
@LucasTran380381 Thanks, can you please squash the translation commits accoridng to the migration guide?

**Comment by LucasTran380381** [comment]
> @LucasTran380381 Thanks, can you please squash the translation commits accoridng to the migration guide?

sqaushed commit of translator. Thanks for review

**Review by bosd — APPROVED** [review]
LGTM

**Review by henrybackman — APPROVED** [review]

**Review by TDu — COMMENTED** [review]
LG, but I don't know what is this commit https://github.com/OCA/community-data-files/pull/216/commits/8e2e2aee0a723e85da091a10458f4c3c8dd69368

**Comment by LucasTran380381** [comment]
> LG, but I don't know what is this commit [8e2e2ae](https://github.com/OCA/community-data-files/commit/8e2e2aee0a723e85da091a10458f4c3c8dd69368)

It will remove warning odoo not have test-case module

**Comment by henrybackman** [comment]
> > LG, but I don't know what is this commit [8e2e2ae](https://github.com/OCA/community-data-files/commit/8e2e2aee0a723e85da091a10458f4c3c8dd69368)
> 
> It will remove warning odoo not have test-case module

There was a small comment on another PR about this:
- https://github.com/OCA/intrastat-extrastat/pull/290#pullrequestreview-2464299214

**Comment by LucasTran380381** [comment]
> > > LG, but I don't know what is this commit [8e2e2ae](https://github.com/OCA/community-data-files/commit/8e2e2aee0a723e85da091a10458f4c3c8dd69368)
> > 
> > 
> > It will remove warning odoo not have test-case module
> 
> There was a small comment on another PR about this:
> 
> * [[18.0][MIG] product_harmonized_system_delivery: Migration to 18.0 intrastat-extrastat#290 (review)](https://github.com/OCA/intrastat-extrastat/pull/290#pullrequestreview-2464299214)

will update pattern warning. thanks

**Review by sebalix — APPROVED** [review]

**Comment by bosd** [comment]
Any chance to superseed/implement the uom code like discussed in https://github.com/OCA/community-data-files/pull/202

(Can be a separate PR, I just wanted to raise awareness to that pr.)

**Review by alexis-via — APPROVED** [review]

**Comment by alexis-via** [comment]
@LucasTran380381 I'll merge as soon as you resolve the conflit

**Comment by LucasTran380381** [comment]
> @LucasTran380381 I'll merge as soon as you resolve the conflit

@alexis-via conflict resolved. Thanks

**Pull request merged**
