### PR TITLE
[16.0][IMP] community-data-files: test performance improvement

### PR DESCRIPTION
**Pull request by josep-tecnativa**
CC @Tecnativa TT45458

### CODE REVIEW

**Comment by josep-tecnativa** [comment]
ping @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Comment by pedrobaeza** [comment]
Oh, wait, it's red...

**Comment by pedrobaeza** [comment]
`ImportError: cannot import name 'DISABLED_MAIL_CONTEXT' from 'odoo.tests.common'`

Please check the path for this.

**Comment by josep-tecnativa** [comment]
> `ImportError: cannot import name 'DISABLED_MAIL_CONTEXT' from 'odoo.tests.common'`
> 
> Please check the path for this.

Done, thanks for the review

**Comment by pedrobaeza** [comment]
Thanks, we will need to adapt the comment in v15 to this path. A pity that is not best located.

/ocabot merge patch

**Pull request merged**
