### PR TITLE
 [17.0][MIG] base_bank_from_iban: Migration to 17.0 

### PR DESCRIPTION
**Pull request by javierobcn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please remove the deb file in the commit that is adding it.

**Comment by pedrobaeza** [comment]
The deb is added in the pre-commit auto-fixes and removed in the following commit, so that's double useless diff. Please remove it in the first one.

**Comment by peluko00** [comment]
Working!

**Review by peluko00 — APPROVED** [review]

**Comment by javierobcn** [comment]
Module migrated to version 17.0

cc https://github.com/APSL 148577 

@miquelalzanillas @lbarry-apsl @peluko00 @samoros1 please review

Issue https://github.com/OCA/community-data-files/issues/177

**Comment by javierobcn** [comment]
> The deb is added in the pre-commit auto-fixes and removed in the following commit, so that's double useless diff. Please remove it in the first one.

Hi @pedrobaeza done!

**Comment by pedrobaeza** [comment]
The pre-commit fixes commits seems to be gone now.

**Comment by javierobcn** [comment]
> The pre-commit fixes commits seems to be gone now.

hi @pedrobaeza done!, sorry :)

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump
/ocabot migration base_bank_from_iban

**Pull request merged**
