### PR TITLE
[14.0][MIG] account_payment_unece

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by alexis-via** [comment]
Requires PR #98  and https://github.com/OCA/bank-payment/pull/744

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Similar comments as account_tax_unece

**Comment by pedrobaeza** [comment]
You can take the occasion to rebase when the main module is merged.

**Review by astirpe — CHANGES_REQUESTED** [review]
Same comment as https://github.com/OCA/community-data-files/pull/99#discussion_r510832164

**Review by astirpe — APPROVED** [review]

**Comment by phuctranfxvn** [comment]
Hello, I think you should include `setup/account_payment_unece` in your PR. This will be required for other migration.
Thanks

**Comment by astirpe** [comment]
Just squash the last two commits and this PR can be merged IMO

**Comment by rconjour** [comment]
I agree with @astirpe , please squas the last two commits, and we can continue with merging :).

**Review by rconjour — APPROVED** [review]

**Comment by manengel** [comment]
Hello @alexis-via ,
this Pull Request has been open since a while and there was quite alot of activity.
Do you plan to continue / finish the work here? It would be great to know, thank you in advance.

**Comment by rconjour** [comment]
@alexis-via @manengel created superseding PR https://github.com/OCA/community-data-files/pull/107 so we can get this merged, and continue on the edi repo.

**Comment by StefanRijnhart** [comment]
Continued on #107

**Pull request closed without merging**
