### PR TITLE
12.0 mig account payment unece

### PR DESCRIPTION
**Pull request by levkar**
Depends on:

- [x] base_unece

### CODE REVIEW

**Comment by astirpe** [comment]
Why did you remove the test files?

**Comment by levkar** [comment]
it is not testing anything in this module and it is necessary remove account_tax_unece dependency.

**Comment by astirpe** [comment]
Ok, I see. You moved them to `account_tax_unece`. Thanks!

**Comment by pedrobaeza** [comment]
Can you please rebase now that base module has been merged? I put the README by fragments in the base one. Maybe you can do the same for this one.

**Comment by alexis-via** [comment]
Code review and tests OK.
I made a suggestion in this PR https://github.com/levkar/community-data-files/pull/2
Then it can be merged.

**Review by alexis-via — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Travis is now stuck, but I merge after squashing a bit the commit history + adding README by fragments. @levkar I have added you as contributor in all the modules as you have made the migration.

**Pull request merged**
