### PR TITLE
[13.0][MIG] account_payment_unece

### PR DESCRIPTION
**Pull request by astirpe**
Depends on:

- [x] base_unece: https://github.com/OCA/community-data-files/pull/73
- [x] account_payment_mode: https://github.com/OCA/bank-payment/pull/636

### CODE REVIEW

**Comment by CasVissers-360ERP** [comment]
@astirpe 
Why is the readme folder in capital letters? Normally lowercase?

**Review by CasVissers-360ERP — APPROVED** [review]
👍 LGTM

**Review by alexis-via — APPROVED** [review]

**Comment by alexis-via** [comment]
pfff, stupid bot...

**Pull request merged**
