### PR TITLE
12.0 mig base currency iso 4217

### PR DESCRIPTION
**Pull request by levkar**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@levkar can you please rebase for having a clean branch?

**Comment by pedrobaeza** [comment]
Not really a rebase, but a merge what you have done.

**Comment by levkar** [comment]
We went through this before. Nothing really special on this PR. Diff is due to change in currency list in 12.0, untraceable due to tab usage instead of space in 11.0 version of this add-on. I am quite busy and don't want to slow down the migration. You can either wait until i find time for it or just make use of this to migrate.

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM, but I can't understand the changes done in `res_currency_data.xml` 🤷‍♂️

**Pull request merged**
