### PR TITLE
[MIG] l10n_eu_nace : Migrated to 10.0

### PR DESCRIPTION
**Pull request by mayjo79**
In order to migrate soon l10n_fr_naf_ape, I need to migrate before l10n_eu_nace.
It's my first contribution to OCA so excuse me in advance for mistakes .

### CODE REVIEW

**Comment by mayjo79** [comment]
Hey OCA,
I sent a mail this morning with my signed CLA.

**Review by yajo — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please cherry-pick last commit from 9.0: https://github.com/OCA/community-data-files/commit/b14c35c36114e8c77fcd229b3f60c2353de76212

**Comment by mayjo79** [comment]
@pedrobaeza could you help me to do "git cherry-pick" ? It's my first contribution to OCA !!

**Comment by pedrobaeza** [comment]
In your branch, add the remote from OCA if you don't have it:
```
git remote add OCA https://github.com/OCA/community-data-files
```
fetch the data for this remote
```
git fetch OCA
```
and cherry-pick the commit
```
git cherry-pick b14c35c
```

**Comment by mayjo79** [comment]
@pedrobaeza I executed these 3 commands. No need of "git push" ?

**Comment by pedrobaeza** [comment]
Well, of course. I specified the local operations, but then you need to push to your remote branch.

**Comment by pedrobaeza** [comment]
Cool, you did it!

**Review by pedrobaeza — APPROVED** [review]

**Review by yajo — APPROVED** [review]
Functional review, and thanks for the cherry pick!

**Comment by bealdav** [comment]
thanks @pedrobaeza @Yajo for your time for new contributors.

@mayjo79 this is the first not the last.

**Pull request merged**
