### PR TITLE
[10.0][FIX] base_iso3166: Limit pycountry version for deprecated support

### PR DESCRIPTION
**Pull request by rousseldenis**
Stop pycountry version to current implementation.

### CODE REVIEW

**Comment by rousseldenis** [comment]
@OCA/core-maintainers

**Comment by sbidoul** [comment]
Why do you need to do this ?

**Comment by rousseldenis** [comment]
> Why do you need to do this ?

@sbidoul Because of this commit in the next version : https://github.com/flyingcircusio/pycountry/commit/71a3b4275c8ce20433708f19bb4187bc39bac08d

**Review by hbrunn — APPROVED** [review]

**Comment by angelmoya** [comment]
Can you add version to requirements.txt?

**Comment by xAdrianC-Kernet** [comment]
change is needed but as @angelmoya sais need to add in requirements.txt @rousseldenis

**Comment by rousseldenis** [comment]
@xAdrianC-Kernet Nope. Travis will not build.

We need to switch to github actions.

**Comment by rousseldenis** [comment]
@OCA/core-maintainers

**Pull request closed without merging**
