### PR TITLE
[14.0][MIG] l10n_eu_nace: Migration to 14.0

### PR DESCRIPTION
**Pull request by ernestotejeda**
Cc @Tecnativa TT32109

Supersedes https://github.com/OCA/community-data-files/pull/124

### CODE REVIEW

**Comment by ernestotejeda** [comment]
ping @pedrobaeza @cvinh

**Review by chienandalu — APPROVED** [review]
Thanks :)

**Review by pedrobaeza — APPROVED** [review]
Functional review at runboat and code review of the migration commit

**Pull request merged**
