### PR TITLE
[12.0][MIG] product_uom_unece > uom_unece: Migration to 12.0

### PR DESCRIPTION
**Pull request by levkar**
Depends on:

- [x] base_unece: #50

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you rebase this one?

**Review by alexis-via — APPROVED** [review]
Code review AND tests. Ready to merge.

**Comment by pedrobaeza** [comment]
The module should be renamed now to `uom_unece` for being inline with Odoo core. May I do it and fix also the commit history?

**Comment by levkar** [comment]
> The module should be renamed now to `uom_unece` for being inline with Odoo core. May I do it and fix also the commit history?

sure. thanks.

**Comment by pedrobaeza** [comment]
I have rewritten the history with `filter-branch` for having `uom_unece` name for all commits for easing future migrations (v13 and so on), added README by fragments, and added the OpenUpgrade rename operation in https://github.com/OCA/OpenUpgrade/commit/a591ab5b5e40e69785775e955095ac1b329ede34.

Waiting for CIs to merge.

**Pull request merged**
