### PR TITLE
[16.0][MIG]: l10n_eu_product_adr: Migration to 16.0

### PR DESCRIPTION
**Pull request by igallart**

### CODE REVIEW

**Comment by l-magnani** [comment]
Hi, why has this PR never been merged? 
@igallart is the module working? 
Thanks

**Comment by remyakrishnann** [comment]
HI @igallart, I’m working on the 16.0 migration for this module. Would you be able to reopen this PR if the branch is still available? 
If reopening is no longer possible or you prefer not to continue with this branch, please let me know —I can create a new PR that references this one.

**Comment by igallart** [comment]
@remyakrishnann , I'm sorry, the branch isn't available, it's from 2023...!

**Comment by remyakrishnann** [comment]
@igallart Thanks for checking. I’ll prepare a new 16.0 migration PR based on the current 16.0 branch and reference this PR for context.

**Pull request closed without merging**
