### PR TITLE
[UPD] pycountry (16.11.27.1) attributes with underscore

### PR DESCRIPTION
**Pull request by ljsalvatierra-binovo**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please sign CLA

**Comment by pedrobaeza** [comment]
Have you signed CLA?

**Comment by ljsalvatierra-binovo** [comment]
I'm swamped at work sorry, i'll do it ASAP.

**Comment by ljsalvatierra-binovo** [comment]
Signed and sent!

**Comment by ljsalvatierra-binovo** [comment]
It appears that my commit is too small and can't pass the test, is there anything i should do?

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Please check via `getattr` method if the module has one function or the other, so you don't force to update the library (as this is silenced with the try).

**Review by alexis-via — APPROVED** [review]

**Comment by pedrobaeza** [comment]
My comment still applies

**Review by alexis-via — APPROVED** [review]

**Pull request closed without merging**
