### PR TITLE
[ADD] trivial migration of *_unece modules

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There's no commit history nor changes in version in manifest nor README.

**Comment by hbrunn** [comment]
oh, seems i git checked out those modules to see how much there's todo, and then forgot to do it the right way afterwards. Thanks for the heads up!

**Comment by pedrobaeza** [comment]
@alexis-via can you review here?

**Review by pedrobaeza — APPROVED** [review]
I will squash a bit the commit history when merging

**Comment by alexis-via** [comment]
I don't see the module account_payment_unece , but the title of the PR says you ported *_unece module...

**Comment by alexis-via** [comment]
I made a minor improvement in my v10 PR ; you may like to replay this commit: https://github.com/OCA/community-data-files/pull/17/commits/3896c05db9a4001630a3203cc7ba14833cf2846c
But this can be done later.

**Review by alexis-via — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
Although there's some big headers and outdated bug tracker links, but it doesn't worth to retain this anymore

**Pull request merged**
