### PR TITLE
[11.0][IMP] Add the number of digits according the ISO 4217

### PR DESCRIPTION
**Pull request by sylvainvh**
I'm not using the field rounding because I want to make the different between the number of digits (according ISO 4217) and how the user want to display this currency

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't the field better named `digits_number`?

**Comment by sylvainvh** [comment]
Hi @pedrobaeza , you right ! I will change the field name

**Comment by sylvainvh** [comment]
Done !

**Review by pedrobaeza — APPROVED** [review]

**Comment by sylvainvh** [comment]
Someone to validate my PR ?

**Comment by pedrobaeza** [comment]
Let's fast track this as straight-forward

**Pull request merged**
