### PR TITLE
[16.0][MIG] base_currency_iso_4217: Migration to 16.0

### PR DESCRIPTION
**Pull request by BT-anieto**

### CODE REVIEW

**Comment by BT-anieto** [comment]
Good morning @JordiBForgeFlow Could you take a look? Thanks before hand

**Review by BT-aleonard — APPROVED** [review]
LTGM, thanks for migrating!

**Review by BT-mrobles — APPROVED** [review]
LGTM!

**Comment by BT-anieto** [comment]
Good morning @pedrobaeza,

Could you check this PR? I don't know who to contact since there is no maintainer (or at least I don't know where to find it

Thank you very much

**Pull request merged**
