### PR TITLE
[17.0][MIG] account_tax_unece: Migration to 17.0

### PR DESCRIPTION
**Pull request by nguyenminhchien**

### CODE REVIEW

**Review by gurneyalex — APPROVED** [review]

**Comment by alexis-via** [comment]
All good. I suggested a small improvement here: https://github.com/nguyenminhchien/community-data-files/pull/2

**Comment by nguyenminhchien** [comment]
> All good. I suggested a small improvement here: [nguyenminhchien#2](https://github.com/nguyenminhchien/community-data-files/pull/2)

I picked your commit, thanks.

**Review by alexis-via — APPROVED** [review]

**Comment by alexis-via** [comment]
@nguyenminhchien base_unece has been merged. So you rebase, remove your commit "DON'T MERGE" and it should be green.

**Comment by nguyenminhchien** [comment]
> @nguyenminhchien base_unece has been merged. So you rebase, remove your commit "DON'T MERGE" and it should be green.

Updated!

**Pull request merged**
