### PR TITLE
[17.0][MIG] uom_unece: Migration to 17.0

### PR DESCRIPTION
**Pull request by youelEl**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the contribution. Please name pull requests properly as I have done it with this one.

/ocabot merge uom_unece

**Comment by alexis-via** [comment]
I propose to supersede this PR with mine https://github.com/OCA/community-data-files/pull/186 that include the fix on the kilometer UNECE code.

**Comment by bosd** [comment]
Looks like this one can be closed as the superseeding pr #186 is merged

**Pull request closed without merging**
