### PR TITLE
[12.0][MIG]  account_payment_unece: add migration scripts

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Add migration scripts for `account_payment_unece`.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
But this is not something about migration, but maybe incorrect module definition. Are original XML-IDs noupdate? If not, although this module put noupdate="1", they will remain as noupdate="0". If yes, then this module must modify them through post_init_hook, not with XML data.

**Comment by MiquelRForgeFlow** [comment]
Original xmlids in `account` are also noupdate="1".

**Comment by pedrobaeza** [comment]
Then installing this module doesn't work at all with that payment modes. As said, this is not migration script, but post_init_hook. If previous version is the same, you would need a migration script calling post_init_hook.

**Comment by MiquelRForgeFlow** [comment]
what do you mean with "if previous version is the same"? In v11 they were ref=payment_means_31 and in this v12 they are ref=payment_means_30.

**Comment by pedrobaeza** [comment]
Then none of them versions are going to work installing from scratch. That data is not going to be populated when installing the module. You need to put the post_init_hook and in this 12.0 version, add this migration script, but calling the post_init_hook.

**Comment by MiquelRForgeFlow** [comment]
ok

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza is it ok, now? 🤔

**Comment by pedrobaeza** [comment]
The same comment about noupdate records in init mode, so please fix this and use load noupdate records in migration scripts.

**Comment by MiquelRForgeFlow** [comment]
done

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
