### PR TITLE
[11.0][MIG] base unece

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by astirpe** [comment]
I added the `def name_get()` because I previously removed the `_rec_name = 'display_name'` line.
The reason why I removed `_rec_name` is because of a very annoying warning
 in the log of Odoo, regarding the `_compute_display_name()` decorator.

**Review by yung-wang — APPROVED** [review]
Works wel, approved

**Comment by pedrobaeza** [comment]
Squashing the first 2 commits this is ready to be merged.

**Comment by astirpe** [comment]
@pedrobaeza done!

**Comment by pedrobaeza** [comment]
Well, I was talking about the first commits from Alexis, where there is a useless commit called "Update version number and use short headers"

**Comment by astirpe** [comment]
@pedrobaeza sorry, I misunderstood. Done.

**Comment by pedrobaeza** [comment]
Thanks!

**Pull request merged**
