### PR TITLE
[11.0] iso 4217 Fixed data files, added decimals, python reformat

### PR DESCRIPTION
**Pull request by levkar**
Fixed data files, added decimals, python reformat

### CODE REVIEW

**Comment by levkar** [comment]
closes #44 

Some new currencies were not in odoo base (they are not added) and some historic currencies were still there (they weren't updated).

@jbeficent

**Comment by pedrobaeza** [comment]
Why the diff on the XML is so big?

**Comment by levkar** [comment]
I rebuilt the whole XML. No spaces between records would be the reason. Too many changes anyway.

**Comment by pedrobaeza** [comment]
It would be good to let that blank lines to reduce the diff at maximum and review only the real changes. Is it possible?

**Comment by levkar** [comment]
I put spaces but diff is still bad. It should be tabs. Are we supposed to use spaces or tabs in XMLs?

**Comment by pedrobaeza** [comment]
Ouch, I see...

Indeed, the agreement is to use spaces, so we don't gain anything as we shouldn't let that incorrect indentation. @jbeficent please use always spaces as indentation. There's a warning about that on Travis, but not blocking right now.

Then if you prefer, you can remove again the empty line, as I thought it was the cause for the large diff. Sorry for the noise.

**Comment by levkar** [comment]
We can keep it, no problem. I am used to hard OCA accept conditions :+1: 

Once accepted I will send 12.0 version.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
